[project]
name = 'collide-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.liquidity-pool]
path = 'contracts/liquidity-pool.clar'
clarity_version = 3
epoch = 3.0

[contracts.mintandburn]
path = 'contracts/mintandburn.clar'
clarity_version = 3
epoch = 3.0

[contracts.tnx-rewards]
path = 'contracts/tnx-rewards.clar'
clarity_version = 3
epoch = 3.0

[contracts.tnx-token]
path = 'contracts/tnx-token.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
